spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: user
app:
  provided-resources:
    users: provided-data/user.csv
    books: provided-data/books.csv
    borrow-info: provided-data/borrowed.csv